# Generated by Django 3.2.6 on 2021-09-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('nightstay', models.BooleanField(default=False)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('induction', models.CharField(max_length=50)),
                ('emergency_name', models.CharField(max_length=50)),
                ('emergency_phone', models.IntegerField()),
                ('emergency_relation', models.CharField(max_length=50)),
            ],
        ),
    ]
