# Generated by Django 3.2.6 on 2021-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='site',
        ),
        migrations.AddField(
            model_name='site',
            name='visitor',
            field=models.ManyToManyField(to='survey.Visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-07 06:17:06', editable=False),
        ),
    ]
