# Generated by Django 3.2.6 on 2021-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('nightstay', models.BooleanField(default=False)),
                ('checkin', models.DateTimeField()),
                ('planned_checkout', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
