# Generated by Django 3.2.6 on 2021-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210907_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-08 21:40:49', editable=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkout',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
