# Generated by Django 3.2.6 on 2021-09-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210914_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-14 09:08:25', editable=False),
        ),
    ]
