# Generated by Django 3.2.6 on 2021-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210909_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='visitors',
            field=models.ManyToManyField(blank=True, null=True, to='survey.Visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-09 19:25:10', editable=False),
        ),
    ]
