# Generated by Django 3.2.6 on 2021-09-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210909_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='visitor',
        ),
        migrations.AddField(
            model_name='visitor',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.history'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-09 21:50:27', editable=False),
        ),
    ]
