# Generated by Django 3.2.6 on 2021-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_visitor_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='visitors',
            field=models.ManyToManyField(blank=True, to='survey.Visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-15 17:38:46', editable=False),
        ),
    ]
