# Generated by Django 3.2.6 on 2021-09-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210907_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='checkout',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-07 03:15:27', editable=False),
        ),
    ]
