# Generated by Django 3.2.6 on 2021-09-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210907_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='checkout',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-07 03:16:52', editable=False),
        ),
    ]
