# Generated by Django 3.2.6 on 2021-09-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210915_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-17 11:02:22', editable=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
