# Generated by Django 3.2.6 on 2021-09-07 03:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210907_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-07 03:18:19', editable=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
