# Generated by Django 3.2.6 on 2021-09-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210917_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-17 12:39:27', editable=False),
        ),
    ]
