# Generated by Django 3.2.6 on 2021-09-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_visitor_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(default='2021-09-17 12:40:15', editable=False),
        ),
    ]
